### ISSUE TITLE
code

### ISSUE THREAD

**Issue by zhao123ying** [Jarvis73/FPTrans#1]
Dear author, I have recently read your work FPTrans. I am very interested in your work and appreciate your contribution. I would like to ask when the relevant code will be released?

**Comment by Jarvis73** [comment]
Hi, @zhao123ying. The code has been released. Thanks for your attention.

**Comment by zhao123ying** [comment]
OK.Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jian-Wei ***@***.***&gt;; 
发送时间: 2022年11月24日(星期四) 中午1:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jarvis73/FPTrans] code (Issue #1)





 
Hi, @zhao123ying. The code has been released. Thanks for your attention.
