### ISSUE TITLE
关于代码promt generation的问题

### ISSUE THREAD

**Issue by DreamerrW** [Jarvis73/FPTrans#4]
您好！我看了您的文章和代码，现在有一点疑惑的是：
3.3.2节Prompt Generation中，文中说在生成了C-维的平均向量后会将其扩展到G×C维的和token一样的东西，然后和token进行拼接我好奇这里G是代表什么意思，以及我在您的代码中好像没有看到有这一步操作...

**Comment by DreamerrW** [comment]
期待您的回答！

**Comment by Jarvis73** [comment]
@DreamerrW 
`G` is the size of a learnable token. The learnable token tensor (`self.prompt_tokens`) is designed to have the total shape of `[bank_size, G, embed_dim]`, where `bank_size` denotes the token pool size, and each token in the pool has a size of `[G, embed_dim]`. In other words, one can think of a "token" as a group of vectors where `G` is the number of vectors. 

For each foreground/background mean feature with size `[embed_dim]`, we broadcast it to `[G, embed_dim]`, and then we can add it to a randomly selected learnable token.

**Comment by DreamerrW** [comment]
Thanks!
