### ISSUE TITLE
Why is the feature extractor not fixed?

### ISSUE THREAD

**Issue by XiaoBuL** [Jarvis73/FPTrans#6]
Hi,

Thanks for your great job! I have a question why is the feature extractor not fixed, which is different from the most common FSS methods? 

Regards, 
MS

**Comment by Jarvis73** [comment]
HI, @XiaoBuL 

Yes. Actually, we mainly fine-tune the feature extractor for adapting the training dataset. For more details please see Section 2.2 in the Paper.

Jian-Wei
